# Generated by Django 6.0.7 on 2026-07-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('service', models.CharField(choices=[('Window', 'Window'), ('Door', 'Door'), ('Ceiling', 'Ceiling'), ('Glass', 'Glass'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
